server:
  port: 8081

logging:  
  file:
    name: logs/app.log
    max-size: 10MB
    max-history: 5

management:
  endpoints:
    web:
      exposure:
        include: "refresh"

remon:
  urls:
    - http://httpbin.org:80
    - http://partner.sktelecom.com/bp/login.do
  domains:
    "[httpbin.org:80]":
      - 44.197.84.54:80
      - 3.224.224.8:80
#      - 127.0.0.1:81
#      - 23.22.173.247:80
    "[http://partnersso.sktelecom.com]":
      - 3.33.139.32:80
#      - 223.130.195.95
